icon-project/icon-bridge

- cmd/iconbridge/chain/near/api.go
- cmd/iconbridge/chain/near/client.go
- cmd/iconbridge/chain/near/errors/base.go
- cmd/iconbridge/chain/near/errors/block_notification_errors.go
- cmd/iconbridge/chain/near/receiver.go
- cmd/iconbridge/chain/near/types/block_notification.go
> #387 Improve block monitoring performance

- javascore/bts/src/main/java/foundation/icon/btp/bts/BTPTokenService.java
Avoids accidental resetting of serial numbers
> Update variables only if null for javascore upgrade

- devnet/docker/icon-bsc/scripts/bmc.js
- devnet/docker/icon-bsc/scripts/bts.js
- devnet/docker/icon-bsc/scripts/changeDeployer.javascore.sh
- devnet/docker/icon-bsc/scripts/changeOwner.javascore.sh
- devnet/docker/icon-bsc/scripts/changeOwner.solidity.sh
1. Change deployer in javascore BTS and BMC
2. Add/remove owner in javascore BTS and BMC
3. Add/remove owner in solidity BTS and BMC
> feat/395 Add script to change owners

- rust/near/bsh/bts/src/coin_management.rs
- rust/near/bsh/bts/src/lib.rs
> style(bts): Change `tokenlimit` to `token_limit`

- rust/near/bsh/bts/src/lib.rs
- rust/near/bsh/bts/src/upgrade.rs
> feat(bts): add migrate method

- devnet/docker/icon-bsc/scripts/deploysc.sh
- devnet/docker/icon-bsc/scripts/generate_e2e_config.sh
- devnet/docker/icon-bsc/scripts/provision.sh
> story(build): add script to generate e2e config during deployment (#493)

- javascore/bts/src/test/java/foundation/icon/btp/bts/AbstractBTPTokenService.java
- javascore/bts/src/test/java/foundation/icon/btp/bts/BTSTest.java
> feat(bts): Add unit test coverage

- doc/testnet_deployment.json
> feat(docs): add testnet deployment network and contract details

- devnet/docker/icon-bsc/scripts/generate_e2e_config.sh
> feat(build): use god wallet path on e2e config by default (#525)

- CODEOWNERS
> chore: add codeowners for docs/

- rust/near/bsh/bts/src/coin_management.rs
> fix(bts): moved coin method to public

- rust/near/bsh/bts/src/coin_management.rs
> feat(bts): Add token_account  field for Mint & Burn event log

- rust/near/bsh/bts/src/coin_management.rs
>  feat(bts):  implement new event log for register event

- rust/near/bsh/bts/src/accounting.rs
- rust/near/bsh/bts/src/external/native_coin.rs
- rust/near/bsh/bts/tests/test_coin_transfer.rs
- rust/near/bsh/bts/tests/test_token_transfer.rs
> fix(bts): add  token_name to withdraw event logging

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/task.md
- .github/ISSUE_TEMPLATE/test-scenario.md
- .github/ISSUE_TEMPLATE/user-story.md
Update "about" information, add task issue.
> chore: add task issue

- codecov.yml
> fix: codecov.yml file with patch reporting

- .github/workflows/deploy-testnet-workflow.yml
> feat(deployment): add schedule and set branch for full bmr testnet run

- javascore/bmc/build.gradle
- javascore/bmc/src/test/java/foundation/icon/btp/bmc/AbstractBTPMessageCenterTest.java
- javascore/bmc/src/test/java/foundation/icon/btp/bmc/BTPMessageCenterTest.java
> test(bmc): Add setter getter tests for javascore bmc

- rust/near/bmc/tests/test_messaging.rs
- rust/near/bsh/bts/src/coin_management.rs
- rust/near/bsh/bts/src/messaging.rs
- rust/near/bsh/bts/src/transfer.rs
- rust/near/bsh/bts/tests/test_blacklist_management.rs
- rust/near/bsh/bts/tests/test_token_management.rs
- rust/near/bsh/bts/tests/test_token_transfer.rs
- rust/near/bsh/bts/tests/token.rs
- rust/near/libraries/src/types/messages/token_service.rs
- rust/near/libraries/src/types/token_limit.rs
> feat(bts): update handle btp message to handle messages of type token limitation

- rust/near/libraries/src/rlp/impls.rs
- rust/near/libraries/src/types/transferable_asset.rs
> fix(bts): rlp encoding for large numbers

- CODEOWNERS
Add @MuhammedIrfan to CODEOWNERS
> chore: add MuhammedIrfan to CODEOWNERS

- javascore/bmc/src/test/java/foundation/icon/btp/bmc/AbstractBTPMessageCenterTest.java
- javascore/bmc/src/test/java/foundation/icon/btp/bmc/BTPMessageCenterTest.java
> test(bmc): Add test for relayers #551

- rust/near/bsh/bts/src/coin_management.rs
- rust/near/bsh/bts/tests/test_blacklist_management.rs
- rust/near/bsh/bts/tests/test_coin_management.rs
> fix(bts): update get_token_limit to public method

- rust/near/bsh/bts/src/blacklist_management.rs
- rust/near/bsh/bts/tests/test_blacklist_management.rs
> fix(bts): Update blacklist methods to public

- cmd/iconbridge/chain/substrate-eth/client.go
- cmd/iconbridge/chain/substrate-eth/mocks/IClient.go
- cmd/iconbridge/chain/substrate-eth/receiver_test.go
- cmd/iconbridge/chain/substrate-eth/sender.go
> feat(bmr): fix eth snow calculation fee (#607)

- cmd/iconbridge/chain/near/receiver.go
- cmd/iconbridge/chain/near/receiver_test.go
- cmd/iconbridge/chain/near/tests/mock/data/events/377825.json
- cmd/iconbridge/chain/near/tests/mock/data/events/377826.json
- cmd/iconbridge/chain/near/tests/receiver_subscribe.go
> fix(bmr): filter btp messages for the destination bmc

- cmd/iconbridge/chain/bsc/receiver.go
- cmd/iconbridge/chain/substrate-eth/receiver.go
> perf(bmr): Update snow config (#637)

- docs/api/bsc/bts.md
- docs/api/icon/bts.md
> docs: Add documentation for feeRatio method  #648

- rust/btp-common/src/error.rs
- rust/near/bsh/bts/src/coin_management.rs
- rust/near/bsh/bts/tests/test_coin_management.rs
> fix(bts): get token limit

- rust/near/bmc/src/messaging.rs
- rust/near/bsh/bts/src/assertion.rs
> fix(near): fix btp error

- README.md
> chore: fix README capitalization (Icon -> ICON)

- devnet/docker/icon-bsc/scripts/changeRelayOwner.javascore.arctic.sh
- devnet/docker/icon-bsc/scripts/changeRelayOwner.javascore.sh
- devnet/docker/icon-bsc/scripts/token.javascore.sh
> feat(deployment): script to change relay owner (#744)

- devnet/docker/icon-bsc/scripts/upgrade.sh
> feat(deployment): ICON upgrade script for bmc and bts (#742)

- cmd/iconbridge/chain/substrate-eth/client.go
- cmd/iconbridge/chain/substrate-eth/receiver.go
- cmd/iconbridge/chain/substrate-eth/rx_test.go
- cmd/iconbridge/relay/config.go
- cmd/iconbridge/relay/multi_relay.go
> fix(bmr): error while comparing receipt hash (#748)

- docs/mainnet_deployment.json
Contract addresses for SNOW mainnet deployment and ICZ token
> docs: snow mainnet contracts

- cmd/iconbridge/chain/substrate-eth/receiver.go
- cmd/iconbridge/chain/substrate-eth/rx_test.go
- cmd/iconbridge/chain/substrate-eth/sender.go
- cmd/iconbridge/relay/relay.go
> fix(bmr): submit transaction to pool failed (#760)

- docs/getting-started.md
> docs: add tldr single step prereqs note

- cmd/e2etest/chain/bsc/api_test.go
- cmd/e2etest/chain/icon/api_test.go
- cmd/e2etest/chain/icon/requests.go
- cmd/e2etest/chain/near/requests.go
- cmd/e2etest/chain/snow/api_test.go
- cmd/e2etest/chain/snow/requests.go
- cmd/e2etest/executor/points_generator.go
> fix(e2e): handle wrapped coin intra-chain transfer (#798)

- docs/testnet_deployment.json
> docs: testnet addresses redeployment

- docs/mainnet_deployment.json
- docs/testnet_deployment.json
> docs: Add owner manager address

- devnet/docker/icon-bsc/scripts/bts.js
- devnet/docker/icon-bsc/scripts/token.solidity.sh
- devnet/docker/icon-bsc/scripts/utils.sh
- solidity/bts/migrations/1_deploy_bts.js
> feat: Update script for direct deployment to account for contract upgrades

- javascore/bmc/src/test/java/foundation/icon/btp/bmc/BTPMessageCenterTest.java
> test(bmc): Handle Relay Message when neither source nor destination is ICON chain
